https://www.youtube.com/watch?v=mirZPrWwvao

# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [156]:
import numpy as np

np.__version__  # Numpy 버전 확인

'1.23.5'



---



## 배열 생성

### 리스트로 배열 만들기


#### 1차원 Numpy 배열

In [157]:
a1 = np.array([1, 2, 3])

print(a1)
print(type(a1))             # 타입 확인
print(a1.shape)             # 구조 확인
print(a1[0], a1[1], a1[2])  # 인덱스로 접근

# Numpy 배열 수정
a1[0] = 4
a1[1] = 5
a1[2] = 6

print(a1)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[4 5 6]


#### 2차원 Numpy 배열

In [158]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


#### 3차원 Numpy 배열

In [159]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]])

print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [160]:
np.zeros(10)  # 0으로 채워진 10개의 Numpy 배열

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [161]:
np.ones(10)  # 1로 채워진 10개의 Numpy 배열

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [162]:
np.ones((3, 3))  # 2차원 배열

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [163]:
np.full((3, 3), fill_value=1.23)  # fill_value: 초기 값 지정(정수, 실수)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [164]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [165]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [166]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [167]:
print(a1)
np.zeros_like(a1)

[4 5 6]


array([0, 0, 0])

In [168]:
print(a2)
np.ones_like(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 1, 1])

In [169]:
print(a3)
np.full_like(a3, 10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [170]:
np.arange(0, 30, 2)  # (start, end, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [171]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [172]:
np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [173]:
np.random.random()

0.01619990004815608

In [174]:
np.random.random((3, 3))

array([[0.09897577, 0.59784386, 0.40587155],
       [0.63274333, 0.89895561, 0.31838474],
       [0.85837542, 0.94611152, 0.60829377]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [175]:
np.random.randint(0, 10)  # 범위 지정

6

In [176]:
np.random.randint(0, 10, (3, 3))  # 범위 지정, 구조 지정

array([[5, 6, 9],
       [8, 3, 3],
       [3, 9, 8]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [177]:
np.random.normal(0, 1, size=(3, 3))  # 범위, 사이즈

array([[-0.11405847, -0.78248747, -1.75813879],
       [-0.65769381, -2.44987531,  0.83264763],
       [ 0.55164986,  0.72758652, -0.63954052]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [178]:
np.random.rand(3, 3)

array([[0.78455275, 0.02988395, 0.66812624],
       [0.56152101, 0.87463855, 0.18583825],
       [0.74068181, 0.5043194 , 0.94934647]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [179]:
np.random.randn(3, 3)

array([[ 1.79530487, -1.00131025,  0.12062352],
       [ 0.53104991, -0.41505874,  0.39640008],
       [-0.59611266,  0.8374451 , -1.72208552]])

### 표준 데이터 타입

In [180]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [181]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [182]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [183]:
date = np.array('2020-01-01', dtype=np.datetime64)  # 날짜
date

array('2020-01-01', dtype='datetime64[D]')

In [184]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [185]:
datetime = np.datetime64('2020-06-01 12:00')  # 날짜 + 시간
datetime

numpy.datetime64('2020-06-01T12:00')

In [186]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')  # 날짜 + 시간(초)
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [187]:
def array_info(array):
    print(array)
    print("ndim:", array.ndim)
    print("shape:", array.shape)
    print("dtype:", array.dtype)
    print("size:", array.size)
    print("itemsize:", array.itemsize)  # 원소 하나가 차지하는 사이즈
    print("nbytes:", array.nbytes)      # itemsize * size
    print("strides:", array.strides)    # 다음 값으로 넘어갈 때 필요한 메모리

In [188]:
array_info(a1)

[4 5 6]
ndim: 1
shape: (3,)
dtype: int64
size: 3
itemsize: 8
nbytes: 24
strides: (8,)


In [189]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [190]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [191]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6]
4
6
6
5


In [192]:
print(a2)
print(a2[0, 0])
print(a2[2, 0])
print(a2[-1, 2])
print(a2[-2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
7
9
5


In [193]:
print(a3)
print(a3[0, 0, 0])
print(a3[2, 0, 1])
print(a3[-1, 2, 2])
print(a3[-2, 1, 2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
2
9
6


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [194]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[::2])
print(a1[::-1])

[4 5 6]
[4 5]
[4 5 6]
[4]
[4 6]
[6 5 4]


In [195]:
print(a2)
print(a2[1])
print(a2[1, :])
print(a2[:2, :2])
print(a2[1:, ::-1])
print(a2[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [196]:
print(a1)

bi = [True, False, True]
print(a1[bi])

bi = [True, False, False]
print(a1[bi])

[4 5 6]
[4 6]
[4]


In [197]:
print(a2)

bi = np.random.randint(0, 2, (3, 3), dtype=bool)
print(bi)

print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True  True]
 [False  True  True]
 [False False  True]]
[2 3 5 6 9]


### 팬시 인덱싱(Fancy Indedxing)

In [198]:
print(a1)

print([a1[0], a1[2]])

ind = [0, 2]
print(a1[ind])

ind = np.array([[0, 1],
                [2, 0]])
print(a1[ind])

[4 5 6]
[4, 6]
[4 6]
[[4 5]
 [6 4]]


In [199]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]


---

## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [200]:
print(a1)

b1 = np.insert(a1, 0, 10)
print(b1)

c1 = np.insert(a1, 2, 10)
print(c1)

[4 5 6]
[10  4  5  6]
[ 4  5 10  6]


In [201]:
print(a2)

b2 = np.insert(a2, 1, 10, axis=0)
print(b2)

c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [202]:
print(a1)

a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)

a1[:2] = 9
print(a1)

i = np.array([0, 2])
a1[i] = 0
print(a1)

a1[i] += 4
print(a1)

[4 5 6]
[1 2 3]
[9 9 3]
[0 9 0]
[4 9 4]


In [203]:
print(a2)

a2[0, 0] = 1
a2[1, 1] = 2
a2[2, 2] = 3
a2[0] = 1
print(a2)

a2[1:, 2] = 9
print(a2)

row = np.array([0, 1])
col = np.array([1, 2])
a2[row, col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [204]:
print(a1)

b1 = np.delete(a1, 1)
print(b1)
print(a1)  # 원본 배열에는 적용 X

[4 9 4]
[4 4]
[4 9 4]


In [205]:
print(a2)

b2 = np.delete(a2, 1, axis=0)
print(b2)

c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [206]:
print(a2)

print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)

a2_sub[:, 1] = 0
print(a2_sub)

print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [207]:
print(a2)

a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)

a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)  # 카피를 사용하면 원본 배열에는 적용 X

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [208]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [209]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [210]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [211]:
print(a3)
print(a3.swapaxes(0, 1))
print(a3.swapaxes(1, 2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [212]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [213]:
print(n1)

print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [214]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

n2.resize((5, 2))
print(n2)

[[0 9 5 0 1]
 [0 5 5 0 0]]
[[0 9]
 [5 0]
 [1 0]
 [5 5]
 [0 0]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [215]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

n2.resize((5, 5))
print(n2)

[[0 4 8 1 5]
 [5 5 6 8 8]]
[[0 4 8 1 5]
 [5 5 6 8 8]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [216]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)

n2.resize((3, 3))
print(n2)

[[0 1 4 8 0]
 [7 1 1 0 3]]
[[0 1 4]
 [8 0 7]
 [1 1 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [217]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

b2 = np.arange(10, 19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [218]:
c2 = np.append(a2, b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [219]:
c2 = np.append(a2, b2, axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [220]:
c2 = np.append(a2, b2, axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [221]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])

np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [222]:
c1 = np.array([7, 8, 9])

np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [223]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

np.concatenate([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [224]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [225]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [226]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [227]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [228]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [229]:
a1 = np.arange(0, 10)
print(a1)

b1, c1 = np.split(a1, [5])
print(b1, c1)

b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [230]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [231]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [232]:
a3 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)

b3, c3 = np.dsplit(a3, [2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


---

## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [241]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)  # [1, 2, 3] + [5, 5, 5]

[1 2 3]
[6 7 8]


In [242]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)  # [[1, 2, 3],     [[1, 2, 3]
                #  [1, 2, 3],  +   [1, 2, 3]
                #  [1, 2, 3]]      [1, 2, 3]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [243]:
b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)  # [[1, 2, 3],     [[1, 1, 1]
                #  [1, 2, 3],  +   [2, 2, 2]
                #  [1, 2, 3]]      [3, 3, 3]]

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [259]:
a1 = np.arange(1, 10)
print(a1)

print(a1 + 1)
print(np.add(a1, 1))           # 덧셈

print(a1 - 2)
print(np.subtract(a1, 2))      # 뺄셈

print(-a1)
print(np.negative(a1))         # 단항 음수

print(a1 * 2)
print(np.multiply(a1, 2))      # 곱셈

print(a1 / 2)
print(np.divide(a1, 2))        # 나눗셈

print(a1 // 2)
print(np.floor_divide(a1, 2))  # 나눗셈 내림

print(a1 ** 2)
print(np.power(a1, 2))         # 지수 연산

print(a1 % 2)
print(np.mod(a1, 2))           # 나머지 연산

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[-1  0  1  2  3  4  5  6  7]
[-1  0  1  2  3  4  5  6  7]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [266]:
# 1차원 배열
a1 = np.arange(1, 10)
print(a1)

b1 = np.random.randint(1, 10, size=9)
print(b1)

print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[1 7 4 2 2 9 3 2 9]
[ 2  9  7  6  7 15 10 10 18]
[ 0 -5 -1  2  3 -3  4  6  0]
[ 1 14 12  8 10 54 21 16 81]
[1.         0.28571429 0.75       2.         2.5        0.66666667
 2.33333333 4.         1.        ]
[1 0 0 2 2 0 2 4 1]
[        1       128        81        16        25  10077696       343
        64 387420489]
[0 2 3 0 1 6 1 0 0]


In [268]:
# 2차원 배열
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)

print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[8 9 2]
 [1 5 5]
 [9 7 5]]
[[ 9 11  5]
 [ 5 10 11]
 [16 15 14]]
[[-7 -7  1]
 [ 3  0  1]
 [-2  1  4]]
[[ 8 18  6]
 [ 4 25 30]
 [63 56 45]]
[[0.125      0.22222222 1.5       ]
 [4.         1.         1.2       ]
 [0.77777778 1.14285714 1.8       ]]
[[0 0 1]
 [4 1 1]
 [0 1 1]]
[[       1      512        9]
 [       4     3125     7776]
 [40353607  2097152    59049]]
[[1 2 1]
 [0 0 1]
 [7 1 4]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [272]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)

print(np.absolute(a1))
print(np.abs(a1))

[-2  2 -4  3  8]
[2 2 4 3 8]
[2 2 4 3 8]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [273]:
print(a1)

print(np.square(a1))
print(np.sqrt(a1))

[-2  2 -4  3  8]
[ 4  4 16  9 64]
[       nan 1.41421356        nan 1.73205081 2.82842712]


<ipython-input-273-bb3c40896931>:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


#### 지수와 로그 함수 (Exponential and Log Function)

In [274]:
a1 = np.random.randint(1, 10, size=5)
print(a1)

print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[7 5 7 9 8]
[1096.63315843  148.4131591  1096.63315843 8103.08392758 2980.95798704]
[128.  32. 128. 512. 256.]
[49 25 49 81 64]


In [275]:
print(a1)

print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 5 7 9 8]
[1.94591015 1.60943791 1.94591015 2.19722458 2.07944154]
[2.80735492 2.32192809 2.80735492 3.169925   3.        ]
[0.84509804 0.69897    0.84509804 0.95424251 0.90308999]


#### 삼각 함수(Trigonometrical Function)


In [276]:
t = np.linspace(0, np.pi, 3)
print(t)

print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [277]:
x = [-1, 0, 1]
print(x)

print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [279]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)

print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0))
print(a2.sum(axis=1), np.sum(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
59 59
[17 19 23] [17 19 23]
[15 23 21] [15 23 21]


#### cumsum(): 누적합 계산

In [280]:
print(a2)

print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
[ 2  9 15 24 29 38 44 51 59]
[[ 2  7  6]
 [11 12 15]
 [17 19 23]]
[[ 2  9 15]
 [ 9 14 23]
 [ 6 13 21]]


#### diff(): 차분 계산

In [281]:
print(a2)

print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
[[ 5 -1]
 [-4  4]
 [ 1  1]]
[[ 7 -2  3]
 [-3  2 -1]]
[[ 5 -1]
 [-4  4]
 [ 1  1]]


#### prod(): 곱 계산

In [282]:
print(a2)

print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
11430720
[108 245 432]
[ 84 405 336]


#### cumprod(): 누적곱 계산

In [283]:
print(a2)

print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
[       2       14       84      756     3780    34020   204120  1428840
 11430720]
[[  2   7   6]
 [ 18  35  54]
 [108 245 432]]
[[  2  14  84]
 [  9  45 405]
 [  6  42 336]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [286]:
print(a2)

b2 = np.ones_like(a2)
print(b2)

print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[15 15 15]
 [23 23 23]
 [21 21 21]]
[[15 15 15]
 [23 23 23]
 [21 21 21]]


#### tensordot(): 텐서곱 계산

In [290]:
print(a2)
print(b2)

print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
59
[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]


 [[[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]]
[[15 15 15]
 [23 23 23]
 [21 21 21]]


#### cross(): 벡터곱

In [291]:
x = [1, 2, 3]
y = [4, 5, 6]

print(np.cross(x, y))

[-3  6 -3]


#### inner()/outer(): 내적/외적

In [292]:
print(a2)
print(b2)

print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[15 15 15]
 [23 23 23]
 [21 21 21]]
[[2 2 2 2 2 2 2 2 2]
 [7 7 7 7 7 7 7 7 7]
 [6 6 6 6 6 6 6 6 6]
 [9 9 9 9 9 9 9 9 9]
 [5 5 5 5 5 5 5 5 5]
 [9 9 9 9 9 9 9 9 9]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]]


#### mean(): 평균 계산

In [293]:
print(a2)

print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
6.555555555555555
[5.66666667 6.33333333 7.66666667]
[5.         7.66666667 7.        ]


#### std(): 표준 편차 계산

In [294]:
print(a2)

print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
2.0608041101101566
[2.86744176 0.94280904 1.24721913]
[2.1602469  1.88561808 0.81649658]


#### var(): 분산 계산

In [295]:
print(a2)

print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
4.246913580246914
[8.22222222 0.88888889 1.55555556]
[4.66666667 3.55555556 0.66666667]


#### min(): 최소값

In [296]:
print(a2)

print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
2
[2 5 6]
[2 5 6]


#### max(): 최대값

In [297]:
print(a2)

print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
9
[9 7 9]
[7 9 8]


#### argmin(): 최소값 인덱스

In [298]:
print(a2)

print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
0
[0 1 0]
[0 1 0]


#### argmax(): 최대값 인덱스

In [299]:
print(a2)

print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
3
[1 0 1]
[1 0 2]


#### median(): 중앙값

In [300]:
print(a2)

print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[2 7 6]
 [9 5 9]
 [6 7 8]]
7.0
[6. 7. 8.]
[6. 9. 7.]


#### percentile(): 백분위 수



In [313]:
a1 = [0, 1, 2, 3]
print(a1)

print(np.percentile(a1, [0, 20, 40, 60, 80, 100], method='linear'))  # [변경] interplation -> method
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], method='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], method='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], method='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], method='midpoint'))

[0, 1, 2, 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [318]:
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])
print(a2)

print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [320]:
a2 = np.array([[False, False, True],
               [True, True, True],
               [False, True, True]])
print(a2)

print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [322]:
a1 = np.arange(1, 10)
print(a1)

print(a1 == 5)
print(a1 != 5)
print(a1 < 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [328]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

print(np.sum(a2))
print(np.count_nonzero(a2 > 5))

print(np.sum(a2 > 5))
print(np.sum(a2 > 5, axis=0))
print(np.sum(a2 > 5, axis=1))

print(np.any(a2 > 5))
print(np.any(a2 > 5, axis=0))
print(np.any(a2 > 5, axis=1))

print(np.all(a2 > 5))
print(np.all(a2 > 5, axis=0))
print(np.all(a2 > 5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
True
[ True  True  True]
[False  True  True]
False
[False False False]
[False False  True]


In [331]:
a1 = np.array([1, 2, 3, 4, 5])
b1 = np.array([1, 2, 3, 3, 4])
print(a1)
print(b1)

print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [335]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)

print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [339]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

# and
print((a2 > 5) & (a2 < 8))
print(a2[(a2 > 5) & (a2 < 8)])

# or
print((a2 > 5) | (a2 < 8))
print(a2[(a2 > 5) | (a2 < 8)])

# xor
print((a2 > 5) ^ (a2 < 8))
print(a2[(a2 > 5) ^ (a2 < 8)])

# not
print(~(a2 > 5))
print(a2[~(a2 > 5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [345]:
a1 = np.random.randint(1, 10, size=10)
print(a1)

print(np.sort(a1))
print(a1)  # 원본에 반영 x

print(np.argsort(a1))
print(a1)  # 원본에 반영 x

print(a1.sort())
print(a1)  # 원본에 반영

[6 9 9 1 7 1 1 6 9 3]
[1 1 1 3 6 6 7 9 9 9]
[6 9 9 1 7 1 1 6 9 3]
[3 5 6 9 0 7 4 1 2 8]
[6 9 9 1 7 1 1 6 9 3]
None
[1 1 1 3 6 6 7 9 9 9]


In [347]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)

print(np.sort(a2, axis=0))
print(np.sort(a2, axis=1))

[[2 8 9]
 [2 9 7]
 [3 1 2]]
[[2 1 2]
 [2 8 7]
 [3 9 9]]
[[2 8 9]
 [2 7 9]
 [1 2 3]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [348]:
a1 = np.random.randint(1, 10, size=10)
print(a1)

print(np.partition(a1, 3))

[6 7 2 2 2 7 6 1 4 8]
[2 1 2 2 4 6 6 7 7 8]


In [350]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)

print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[5 6 1 1 5]
 [6 6 4 1 1]
 [6 8 3 7 3]
 [1 5 3 5 6]
 [3 2 1 1 7]]
[[1 1 5 5 6]
 [1 1 4 6 6]
 [3 3 6 7 8]
 [1 3 5 5 6]
 [1 1 2 3 7]]
[[1 5 1 1 1]
 [3 2 1 1 3]
 [5 6 3 1 5]
 [6 6 3 5 6]
 [6 8 4 7 7]]
[[1 1 5 5 6]
 [1 1 4 6 6]
 [3 3 6 7 8]
 [1 3 5 5 6]
 [1 1 2 3 7]]


## 배열 입출력


In [351]:
a2 = np.random.randint(1, 10, size=(5, 5))
print(a2)

np.save("a", a2)

[[6 6 4 3 7]
 [6 5 6 6 9]
 [5 3 7 8 1]
 [5 2 8 7 4]
 [1 4 6 9 8]]


In [352]:
!ls

a.npy  sample_data


In [353]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)

np.savez("ab", a2, b2)

[[1 1 8 4 5]
 [8 6 6 9 4]
 [5 5 1 2 2]
 [3 2 2 9 7]
 [4 4 4 6 8]]


In [354]:
!ls

ab.npz	a.npy  sample_data


In [355]:
npy = np.load("a.npy")
print(npy)

[[6 6 4 3 7]
 [6 5 6 6 9]
 [5 3 7 8 1]
 [5 2 8 7 4]
 [1 4 6 9 8]]


In [358]:
npz = np.load("ab.npz")
print(npz.files)     # .npz 에 저장된 파일 확인
print(npz['arr_0'])  # .npz 에 저장된 파일 1 출력
print(npz['arr_1'])  # .npz 에 저장된 파일 2 출력

['arr_0', 'arr_1']
[[6 6 4 3 7]
 [6 5 6 6 9]
 [5 3 7 8 1]
 [5 2 8 7 4]
 [1 4 6 9 8]]
[[1 1 8 4 5]
 [8 6 6 9 4]
 [5 5 1 2 2]
 [3 2 2 9 7]
 [4 4 4 6 8]]


In [359]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',')

[[6 6 4 3 7]
 [6 5 6 6 9]
 [5 3 7 8 1]
 [5 2 8 7 4]
 [1 4 6 9 8]]


In [360]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [361]:
!cat a.csv

6.000000000000000000e+00,6.000000000000000000e+00,4.000000000000000000e+00,3.000000000000000000e+00,7.000000000000000000e+00
6.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00
5.000000000000000000e+00,3.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,1.000000000000000000e+00
5.000000000000000000e+00,2.000000000000000000e+00,8.000000000000000000e+00,7.000000000000000000e+00,4.000000000000000000e+00
1.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,8.000000000000000000e+00


In [364]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[6. 6. 4. 3. 7.]
 [6. 5. 6. 6. 9.]
 [5. 3. 7. 8. 1.]
 [5. 2. 8. 7. 4.]
 [1. 4. 6. 9. 8.]]


In [365]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4')  # fmt='%.2e'(소수점 둘째 자리)

[[1 1 8 4 5]
 [8 6 6 9 4]
 [5 5 1 2 2]
 [3 2 2 9 7]
 [4 4 4 6 8]]


In [366]:
!cat b.csv

# c1, c2, c3, c4
1.00e+00,1.00e+00,8.00e+00,4.00e+00,5.00e+00
8.00e+00,6.00e+00,6.00e+00,9.00e+00,4.00e+00
5.00e+00,5.00e+00,1.00e+00,2.00e+00,2.00e+00
3.00e+00,2.00e+00,2.00e+00,9.00e+00,7.00e+00
4.00e+00,4.00e+00,4.00e+00,6.00e+00,8.00e+00


In [368]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[1. 1. 8. 4. 5.]
 [8. 6. 6. 9. 4.]
 [5. 5. 1. 2. 2.]
 [3. 2. 2. 9. 7.]
 [4. 4. 4. 6. 8.]]




---

